const char RED_MISSION_1[] = { FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, FORWARD, LEFT, LEFT, BACK, BACK, BACK, BACK };
const char RED_PICKUP_1[] = { EMPTY, EMPTY, LEFT, EMPTY, RIGHT, EMPTY, EMPTY, RIGHT, EMPTY, EMPTY, EMPTY, EMPTY };
const int RED_STEPS_1 = 12;
const char NEUTRAL_MISSION_1[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, RIGHT, RIGHT, LEFT, LEFT, BACK, BACK, BACK, BACK, BACK, BACK, RIGHT };
const char NEUTRAL_PICKUP_1[] = { EMPTY, EMPTY, LEFT, EMPTY, EMPTY, LEFT, EMPTY, RIGHT, LEFT, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY };
const int NEUTRAL_STEPS_1 = 18;


