

/*


const char RED_MISSION_1[] = { FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, FORWARD, LEFT, LEFT, BACK, BACK, BACK, BACK };
const char RED_PICKUP_1[] = { EMPTY, EMPTY, LEFT, EMPTY, RIGHT, EMPTY, EMPTY, RIGHT, EMPTY, EMPTY, EMPTY, EMPTY };
const int RED_STEPS_1 = 12;
const char NEUTRAL_MISSION_1[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, RIGHT, RIGHT, LEFT, LEFT, BACK, BACK, BACK, BACK, BACK, BACK, RIGHT };
const char NEUTRAL_PICKUP_1[] = { EMPTY, EMPTY, LEFT, EMPTY, EMPTY, LEFT, EMPTY, RIGHT, LEFT, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY };
const int NEUTRAL_STEPS_1 = 18;

const char RED_MISSION_2[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, BACK, LEFT, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, LEFT };

const char RED_PICKUP_2[] = { EMPTY, EMPTY, LEFT, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LEFT, EMPTY, EMPTY, EMPTY, EMPTY, LEFT, EMPTY, EMPTY, EMPTY, EMPTY };

const int RED_STEPS_2 = 18;

const char NEUTRAL_MISSION_2[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, BACK, LEFT, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, LEFT };

const char NEUTRAL_PICKUP_2[] = { EMPTY, EMPTY, RIGHT, EMPTY, EMPTY, RIGHT, EMPTY, LEFT, EMPTY, EMPTY, LEFT, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY };

const int NEUTRAL_STEPS_2 = 16;


const char RED_MISSION_3[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, BACK, FORWARD, FORWARD, LEFT, FORWARD, FORWARD, FORWARD };

const char RED_PICKUP_3[] = { EMPTY, EMPTY, EMPTY, EMPTY, LEFT, EMPTY, RIGHT, EMPTY, EMPTY, EMPTY, RIGHT, EMPTY, EMPTY, EMPTY };

const int RED_STEPS_3 = 14;

const char NEUTRAL_MISSION_3[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, RIGHT, FORWARD, RIGHT, LEFT, FORWARD, FORWARD, FORWARD, LEFT };

const char NEUTRAL_PICKUP_3[] = { EMPTY, EMPTY, LEFT, EMPTY, EMPTY, LEFT, LEFT, EMPTY, EMPTY, LEFT, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY };

const int NEUTRAL_STEPS_3 = 16;


const char RED_MISSION_4[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, LEFT, LEFT, FORWARD, FORWARD, FORWARD, FORWARD, FORWARD };

const char RED_PICKUP_4[] = { EMPTY, EMPTY, LEFT, EMPTY, EMPTY, EMPTY, RIGHT, RIGHT, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY };

const int RED_STEPS_4 = 14;

const char NEUTRAL_MISSION_4[] = { FORWARD, FORWARD, FORWARD, FORWARD, FORWARD, RIGHT, FORWARD, RIGHT, FORWARD, FORWARD, RIGHT, LEFT, FORWARD, LEFT };

const char NEUTRAL_PICKUP_4[] = { EMPTY, EMPTY, EMPTY, EMPTY, RIGHT, EMPTY, EMPTY, LEFT, RIGHT, LEFT, EMPTY, EMPTY, EMPTY, EMPTY };

const int NEUTRAL_STEPS_4 = 14;*/

